version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  app:
    image: mongoapidocker:1.0
    depends_on:
      - mongo
    ports:
      - 8083:8083
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/yourdbname
